package com.model;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminId
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminName
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminPassword
     *
     * @mbggenerated
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminXingming
     *
     * @mbggenerated
     */
    private String adminXingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminSex
     *
     * @mbggenerated
     */
    private Integer adminSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminAge
     *
     * @mbggenerated
     */
    private Integer adminAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminPhone
     *
     * @mbggenerated
     */
    private String adminPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminMark
     *
     * @mbggenerated
     */
    private String adminMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminMark1
     *
     * @mbggenerated
     */
    private String adminMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminMark2
     *
     * @mbggenerated
     */
    private String adminMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminMark3
     *
     * @mbggenerated
     */
    private String adminMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminMark4
     *
     * @mbggenerated
     */
    private String adminMark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDate
     *
     * @mbggenerated
     */
    private Date adminDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDate1
     *
     * @mbggenerated
     */
    private Date adminDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDate2
     *
     * @mbggenerated
     */
    private Date adminDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminType
     *
     * @mbggenerated
     */
    private Integer adminType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminType1
     *
     * @mbggenerated
     */
    private Integer adminType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminType2
     *
     * @mbggenerated
     */
    private Integer adminType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDouble
     *
     * @mbggenerated
     */
    private Double adminDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDouble1
     *
     * @mbggenerated
     */
    private Double adminDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminDouble2
     *
     * @mbggenerated
     */
    private Double adminDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminZong
     *
     * @mbggenerated
     */
    private Integer adminZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminZong1
     *
     * @mbggenerated
     */
    private Integer adminZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminZong2
     *
     * @mbggenerated
     */
    private Integer adminZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminImg
     *
     * @mbggenerated
     */
    private String adminImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminImgName
     *
     * @mbggenerated
     */
    private String adminImgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminId
     *
     * @return the value of t_admin.adminId
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminId
     *
     * @param adminId the value for t_admin.adminId
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminName
     *
     * @return the value of t_admin.adminName
     *
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminName
     *
     * @param adminName the value for t_admin.adminName
     *
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminPassword
     *
     * @return the value of t_admin.adminPassword
     *
     * @mbggenerated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminPassword
     *
     * @param adminPassword the value for t_admin.adminPassword
     *
     * @mbggenerated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminXingming
     *
     * @return the value of t_admin.adminXingming
     *
     * @mbggenerated
     */
    public String getAdminXingming() {
        return adminXingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminXingming
     *
     * @param adminXingming the value for t_admin.adminXingming
     *
     * @mbggenerated
     */
    public void setAdminXingming(String adminXingming) {
        this.adminXingming = adminXingming == null ? null : adminXingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminSex
     *
     * @return the value of t_admin.adminSex
     *
     * @mbggenerated
     */
    public Integer getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminSex
     *
     * @param adminSex the value for t_admin.adminSex
     *
     * @mbggenerated
     */
    public void setAdminSex(Integer adminSex) {
        this.adminSex = adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminAge
     *
     * @return the value of t_admin.adminAge
     *
     * @mbggenerated
     */
    public Integer getAdminAge() {
        return adminAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminAge
     *
     * @param adminAge the value for t_admin.adminAge
     *
     * @mbggenerated
     */
    public void setAdminAge(Integer adminAge) {
        this.adminAge = adminAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminPhone
     *
     * @return the value of t_admin.adminPhone
     *
     * @mbggenerated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminPhone
     *
     * @param adminPhone the value for t_admin.adminPhone
     *
     * @mbggenerated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminMark
     *
     * @return the value of t_admin.adminMark
     *
     * @mbggenerated
     */
    public String getAdminMark() {
        return adminMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminMark
     *
     * @param adminMark the value for t_admin.adminMark
     *
     * @mbggenerated
     */
    public void setAdminMark(String adminMark) {
        this.adminMark = adminMark == null ? null : adminMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminMark1
     *
     * @return the value of t_admin.adminMark1
     *
     * @mbggenerated
     */
    public String getAdminMark1() {
        return adminMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminMark1
     *
     * @param adminMark1 the value for t_admin.adminMark1
     *
     * @mbggenerated
     */
    public void setAdminMark1(String adminMark1) {
        this.adminMark1 = adminMark1 == null ? null : adminMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminMark2
     *
     * @return the value of t_admin.adminMark2
     *
     * @mbggenerated
     */
    public String getAdminMark2() {
        return adminMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminMark2
     *
     * @param adminMark2 the value for t_admin.adminMark2
     *
     * @mbggenerated
     */
    public void setAdminMark2(String adminMark2) {
        this.adminMark2 = adminMark2 == null ? null : adminMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminMark3
     *
     * @return the value of t_admin.adminMark3
     *
     * @mbggenerated
     */
    public String getAdminMark3() {
        return adminMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminMark3
     *
     * @param adminMark3 the value for t_admin.adminMark3
     *
     * @mbggenerated
     */
    public void setAdminMark3(String adminMark3) {
        this.adminMark3 = adminMark3 == null ? null : adminMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminMark4
     *
     * @return the value of t_admin.adminMark4
     *
     * @mbggenerated
     */
    public String getAdminMark4() {
        return adminMark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminMark4
     *
     * @param adminMark4 the value for t_admin.adminMark4
     *
     * @mbggenerated
     */
    public void setAdminMark4(String adminMark4) {
        this.adminMark4 = adminMark4 == null ? null : adminMark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDate
     *
     * @return the value of t_admin.adminDate
     *
     * @mbggenerated
     */
    public Date getAdminDate() {
        return adminDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDate
     *
     * @param adminDate the value for t_admin.adminDate
     *
     * @mbggenerated
     */
    public void setAdminDate(Date adminDate) {
        this.adminDate = adminDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDate1
     *
     * @return the value of t_admin.adminDate1
     *
     * @mbggenerated
     */
    public Date getAdminDate1() {
        return adminDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDate1
     *
     * @param adminDate1 the value for t_admin.adminDate1
     *
     * @mbggenerated
     */
    public void setAdminDate1(Date adminDate1) {
        this.adminDate1 = adminDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDate2
     *
     * @return the value of t_admin.adminDate2
     *
     * @mbggenerated
     */
    public Date getAdminDate2() {
        return adminDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDate2
     *
     * @param adminDate2 the value for t_admin.adminDate2
     *
     * @mbggenerated
     */
    public void setAdminDate2(Date adminDate2) {
        this.adminDate2 = adminDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminType
     *
     * @return the value of t_admin.adminType
     *
     * @mbggenerated
     */
    public Integer getAdminType() {
        return adminType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminType
     *
     * @param adminType the value for t_admin.adminType
     *
     * @mbggenerated
     */
    public void setAdminType(Integer adminType) {
        this.adminType = adminType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminType1
     *
     * @return the value of t_admin.adminType1
     *
     * @mbggenerated
     */
    public Integer getAdminType1() {
        return adminType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminType1
     *
     * @param adminType1 the value for t_admin.adminType1
     *
     * @mbggenerated
     */
    public void setAdminType1(Integer adminType1) {
        this.adminType1 = adminType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminType2
     *
     * @return the value of t_admin.adminType2
     *
     * @mbggenerated
     */
    public Integer getAdminType2() {
        return adminType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminType2
     *
     * @param adminType2 the value for t_admin.adminType2
     *
     * @mbggenerated
     */
    public void setAdminType2(Integer adminType2) {
        this.adminType2 = adminType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDouble
     *
     * @return the value of t_admin.adminDouble
     *
     * @mbggenerated
     */
    public Double getAdminDouble() {
        return adminDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDouble
     *
     * @param adminDouble the value for t_admin.adminDouble
     *
     * @mbggenerated
     */
    public void setAdminDouble(Double adminDouble) {
        this.adminDouble = adminDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDouble1
     *
     * @return the value of t_admin.adminDouble1
     *
     * @mbggenerated
     */
    public Double getAdminDouble1() {
        return adminDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDouble1
     *
     * @param adminDouble1 the value for t_admin.adminDouble1
     *
     * @mbggenerated
     */
    public void setAdminDouble1(Double adminDouble1) {
        this.adminDouble1 = adminDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminDouble2
     *
     * @return the value of t_admin.adminDouble2
     *
     * @mbggenerated
     */
    public Double getAdminDouble2() {
        return adminDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminDouble2
     *
     * @param adminDouble2 the value for t_admin.adminDouble2
     *
     * @mbggenerated
     */
    public void setAdminDouble2(Double adminDouble2) {
        this.adminDouble2 = adminDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminZong
     *
     * @return the value of t_admin.adminZong
     *
     * @mbggenerated
     */
    public Integer getAdminZong() {
        return adminZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminZong
     *
     * @param adminZong the value for t_admin.adminZong
     *
     * @mbggenerated
     */
    public void setAdminZong(Integer adminZong) {
        this.adminZong = adminZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminZong1
     *
     * @return the value of t_admin.adminZong1
     *
     * @mbggenerated
     */
    public Integer getAdminZong1() {
        return adminZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminZong1
     *
     * @param adminZong1 the value for t_admin.adminZong1
     *
     * @mbggenerated
     */
    public void setAdminZong1(Integer adminZong1) {
        this.adminZong1 = adminZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminZong2
     *
     * @return the value of t_admin.adminZong2
     *
     * @mbggenerated
     */
    public Integer getAdminZong2() {
        return adminZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminZong2
     *
     * @param adminZong2 the value for t_admin.adminZong2
     *
     * @mbggenerated
     */
    public void setAdminZong2(Integer adminZong2) {
        this.adminZong2 = adminZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminImg
     *
     * @return the value of t_admin.adminImg
     *
     * @mbggenerated
     */
    public String getAdminImg() {
        return adminImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminImg
     *
     * @param adminImg the value for t_admin.adminImg
     *
     * @mbggenerated
     */
    public void setAdminImg(String adminImg) {
        this.adminImg = adminImg == null ? null : adminImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminImgName
     *
     * @return the value of t_admin.adminImgName
     *
     * @mbggenerated
     */
    public String getAdminImgName() {
        return adminImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminImgName
     *
     * @param adminImgName the value for t_admin.adminImgName
     *
     * @mbggenerated
     */
    public void setAdminImgName(String adminImgName) {
        this.adminImgName = adminImgName == null ? null : adminImgName.trim();
    }
}