package com.model;

import java.util.Date;

public class Rizhi {
    private Integer rizhiId;
    private String rizhiName; // 操作人姓名/账号
    private String dengluIp;  // IP地址
    private Date date;        // 操作时间
    private String rizhiType; // 操作类型 (新)
    private String rizhiResult; // 操作结果 (新)
    private String rizhiRemark; // 备注 (新)


    public Integer getRizhiId() {
        return rizhiId;
    }
    public String getRizhiType() { return rizhiType; }
    public void setRizhiType(String rizhiType) { this.rizhiType = rizhiType; }

    public String getRizhiResult() { return rizhiResult; }
    public void setRizhiResult(String rizhiResult) { this.rizhiResult = rizhiResult; }

    public String getRizhiRemark() { return rizhiRemark; }
    public void setRizhiRemark(String rizhiRemark) { this.rizhiRemark = rizhiRemark; }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rizhi.rizhiId
     *
     * @param rizhiId the value for t_rizhi.rizhiId
     *
     * @mbggenerated
     */
    public void setRizhiId(Integer rizhiId) {
        this.rizhiId = rizhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rizhi.rizhiName
     *
     * @return the value of t_rizhi.rizhiName
     *
     * @mbggenerated
     */
    public String getRizhiName() {
        return rizhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rizhi.rizhiName
     *
     * @param rizhiName the value for t_rizhi.rizhiName
     *
     * @mbggenerated
     */
    public void setRizhiName(String rizhiName) {
        this.rizhiName = rizhiName == null ? null : rizhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rizhi.dengluIp
     *
     * @return the value of t_rizhi.dengluIp
     *
     * @mbggenerated
     */
    public String getDengluIp() {
        return dengluIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rizhi.dengluIp
     *
     * @param dengluIp the value for t_rizhi.dengluIp
     *
     * @mbggenerated
     */
    public void setDengluIp(String dengluIp) {
        this.dengluIp = dengluIp == null ? null : dengluIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rizhi.date
     *
     * @return the value of t_rizhi.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rizhi.date
     *
     * @param date the value for t_rizhi.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}