package com.model;

import java.util.Date;

public class Sjpinglun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunId
     *
     * @mbggenerated
     */
    private Integer sjpinglunId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunName
     *
     * @mbggenerated
     */
    private String sjpinglunName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunMark
     *
     * @mbggenerated
     */
    private String sjpinglunMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunMark1
     *
     * @mbggenerated
     */
    private String sjpinglunMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunMark2
     *
     * @mbggenerated
     */
    private String sjpinglunMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunMark3
     *
     * @mbggenerated
     */
    private String sjpinglunMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunDate
     *
     * @mbggenerated
     */
    private Date sjpinglunDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunDate1
     *
     * @mbggenerated
     */
    private Date sjpinglunDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunZong
     *
     * @mbggenerated
     */
    private Integer sjpinglunZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunZong1
     *
     * @mbggenerated
     */
    private Integer sjpinglunZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunZong2
     *
     * @mbggenerated
     */
    private Integer sjpinglunZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunDouble
     *
     * @mbggenerated
     */
    private Double sjpinglunDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunDouble1
     *
     * @mbggenerated
     */
    private Double sjpinglunDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunDouble2
     *
     * @mbggenerated
     */
    private Double sjpinglunDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunType
     *
     * @mbggenerated
     */
    private Integer sjpinglunType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunType1
     *
     * @mbggenerated
     */
    private Integer sjpinglunType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunType2
     *
     * @mbggenerated
     */
    private Integer sjpinglunType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjqitaId
     *
     * @mbggenerated
     */
    private Integer sjqitaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjqitaName
     *
     * @mbggenerated
     */
    private String sjqitaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjlaiyuanName
     *
     * @mbggenerated
     */
    private String sjlaiyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunImg
     *
     * @mbggenerated
     */
    private String sjpinglunImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunImgName
     *
     * @mbggenerated
     */
    private String sjpinglunImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.shujuId
     *
     * @mbggenerated
     */
    private Integer shujuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.shujuName
     *
     * @mbggenerated
     */
    private String shujuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjleixingName
     *
     * @mbggenerated
     */
    private String sjleixingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjxingtaiName
     *
     * @mbggenerated
     */
    private String sjxingtaiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunId
     *
     * @return the value of t_sjpinglun.sjpinglunId
     *
     * @mbggenerated
     */
    public Integer getSjpinglunId() {
        return sjpinglunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunId
     *
     * @param sjpinglunId the value for t_sjpinglun.sjpinglunId
     *
     * @mbggenerated
     */
    public void setSjpinglunId(Integer sjpinglunId) {
        this.sjpinglunId = sjpinglunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunName
     *
     * @return the value of t_sjpinglun.sjpinglunName
     *
     * @mbggenerated
     */
    public String getSjpinglunName() {
        return sjpinglunName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunName
     *
     * @param sjpinglunName the value for t_sjpinglun.sjpinglunName
     *
     * @mbggenerated
     */
    public void setSjpinglunName(String sjpinglunName) {
        this.sjpinglunName = sjpinglunName == null ? null : sjpinglunName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunMark
     *
     * @return the value of t_sjpinglun.sjpinglunMark
     *
     * @mbggenerated
     */
    public String getSjpinglunMark() {
        return sjpinglunMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunMark
     *
     * @param sjpinglunMark the value for t_sjpinglun.sjpinglunMark
     *
     * @mbggenerated
     */
    public void setSjpinglunMark(String sjpinglunMark) {
        this.sjpinglunMark = sjpinglunMark == null ? null : sjpinglunMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunMark1
     *
     * @return the value of t_sjpinglun.sjpinglunMark1
     *
     * @mbggenerated
     */
    public String getSjpinglunMark1() {
        return sjpinglunMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunMark1
     *
     * @param sjpinglunMark1 the value for t_sjpinglun.sjpinglunMark1
     *
     * @mbggenerated
     */
    public void setSjpinglunMark1(String sjpinglunMark1) {
        this.sjpinglunMark1 = sjpinglunMark1 == null ? null : sjpinglunMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunMark2
     *
     * @return the value of t_sjpinglun.sjpinglunMark2
     *
     * @mbggenerated
     */
    public String getSjpinglunMark2() {
        return sjpinglunMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunMark2
     *
     * @param sjpinglunMark2 the value for t_sjpinglun.sjpinglunMark2
     *
     * @mbggenerated
     */
    public void setSjpinglunMark2(String sjpinglunMark2) {
        this.sjpinglunMark2 = sjpinglunMark2 == null ? null : sjpinglunMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunMark3
     *
     * @return the value of t_sjpinglun.sjpinglunMark3
     *
     * @mbggenerated
     */
    public String getSjpinglunMark3() {
        return sjpinglunMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunMark3
     *
     * @param sjpinglunMark3 the value for t_sjpinglun.sjpinglunMark3
     *
     * @mbggenerated
     */
    public void setSjpinglunMark3(String sjpinglunMark3) {
        this.sjpinglunMark3 = sjpinglunMark3 == null ? null : sjpinglunMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunDate
     *
     * @return the value of t_sjpinglun.sjpinglunDate
     *
     * @mbggenerated
     */
    public Date getSjpinglunDate() {
        return sjpinglunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunDate
     *
     * @param sjpinglunDate the value for t_sjpinglun.sjpinglunDate
     *
     * @mbggenerated
     */
    public void setSjpinglunDate(Date sjpinglunDate) {
        this.sjpinglunDate = sjpinglunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunDate1
     *
     * @return the value of t_sjpinglun.sjpinglunDate1
     *
     * @mbggenerated
     */
    public Date getSjpinglunDate1() {
        return sjpinglunDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunDate1
     *
     * @param sjpinglunDate1 the value for t_sjpinglun.sjpinglunDate1
     *
     * @mbggenerated
     */
    public void setSjpinglunDate1(Date sjpinglunDate1) {
        this.sjpinglunDate1 = sjpinglunDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunZong
     *
     * @return the value of t_sjpinglun.sjpinglunZong
     *
     * @mbggenerated
     */
    public Integer getSjpinglunZong() {
        return sjpinglunZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunZong
     *
     * @param sjpinglunZong the value for t_sjpinglun.sjpinglunZong
     *
     * @mbggenerated
     */
    public void setSjpinglunZong(Integer sjpinglunZong) {
        this.sjpinglunZong = sjpinglunZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunZong1
     *
     * @return the value of t_sjpinglun.sjpinglunZong1
     *
     * @mbggenerated
     */
    public Integer getSjpinglunZong1() {
        return sjpinglunZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunZong1
     *
     * @param sjpinglunZong1 the value for t_sjpinglun.sjpinglunZong1
     *
     * @mbggenerated
     */
    public void setSjpinglunZong1(Integer sjpinglunZong1) {
        this.sjpinglunZong1 = sjpinglunZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunZong2
     *
     * @return the value of t_sjpinglun.sjpinglunZong2
     *
     * @mbggenerated
     */
    public Integer getSjpinglunZong2() {
        return sjpinglunZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunZong2
     *
     * @param sjpinglunZong2 the value for t_sjpinglun.sjpinglunZong2
     *
     * @mbggenerated
     */
    public void setSjpinglunZong2(Integer sjpinglunZong2) {
        this.sjpinglunZong2 = sjpinglunZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunDouble
     *
     * @return the value of t_sjpinglun.sjpinglunDouble
     *
     * @mbggenerated
     */
    public Double getSjpinglunDouble() {
        return sjpinglunDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunDouble
     *
     * @param sjpinglunDouble the value for t_sjpinglun.sjpinglunDouble
     *
     * @mbggenerated
     */
    public void setSjpinglunDouble(Double sjpinglunDouble) {
        this.sjpinglunDouble = sjpinglunDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunDouble1
     *
     * @return the value of t_sjpinglun.sjpinglunDouble1
     *
     * @mbggenerated
     */
    public Double getSjpinglunDouble1() {
        return sjpinglunDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunDouble1
     *
     * @param sjpinglunDouble1 the value for t_sjpinglun.sjpinglunDouble1
     *
     * @mbggenerated
     */
    public void setSjpinglunDouble1(Double sjpinglunDouble1) {
        this.sjpinglunDouble1 = sjpinglunDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunDouble2
     *
     * @return the value of t_sjpinglun.sjpinglunDouble2
     *
     * @mbggenerated
     */
    public Double getSjpinglunDouble2() {
        return sjpinglunDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunDouble2
     *
     * @param sjpinglunDouble2 the value for t_sjpinglun.sjpinglunDouble2
     *
     * @mbggenerated
     */
    public void setSjpinglunDouble2(Double sjpinglunDouble2) {
        this.sjpinglunDouble2 = sjpinglunDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunType
     *
     * @return the value of t_sjpinglun.sjpinglunType
     *
     * @mbggenerated
     */
    public Integer getSjpinglunType() {
        return sjpinglunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunType
     *
     * @param sjpinglunType the value for t_sjpinglun.sjpinglunType
     *
     * @mbggenerated
     */
    public void setSjpinglunType(Integer sjpinglunType) {
        this.sjpinglunType = sjpinglunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunType1
     *
     * @return the value of t_sjpinglun.sjpinglunType1
     *
     * @mbggenerated
     */
    public Integer getSjpinglunType1() {
        return sjpinglunType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunType1
     *
     * @param sjpinglunType1 the value for t_sjpinglun.sjpinglunType1
     *
     * @mbggenerated
     */
    public void setSjpinglunType1(Integer sjpinglunType1) {
        this.sjpinglunType1 = sjpinglunType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunType2
     *
     * @return the value of t_sjpinglun.sjpinglunType2
     *
     * @mbggenerated
     */
    public Integer getSjpinglunType2() {
        return sjpinglunType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunType2
     *
     * @param sjpinglunType2 the value for t_sjpinglun.sjpinglunType2
     *
     * @mbggenerated
     */
    public void setSjpinglunType2(Integer sjpinglunType2) {
        this.sjpinglunType2 = sjpinglunType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjqitaId
     *
     * @return the value of t_sjpinglun.sjqitaId
     *
     * @mbggenerated
     */
    public Integer getSjqitaId() {
        return sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjqitaId
     *
     * @param sjqitaId the value for t_sjpinglun.sjqitaId
     *
     * @mbggenerated
     */
    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjqitaName
     *
     * @return the value of t_sjpinglun.sjqitaName
     *
     * @mbggenerated
     */
    public String getSjqitaName() {
        return sjqitaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjqitaName
     *
     * @param sjqitaName the value for t_sjpinglun.sjqitaName
     *
     * @mbggenerated
     */
    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjlaiyuanId
     *
     * @return the value of t_sjpinglun.sjlaiyuanId
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjlaiyuanId
     *
     * @param sjlaiyuanId the value for t_sjpinglun.sjlaiyuanId
     *
     * @mbggenerated
     */
    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjlaiyuanName
     *
     * @return the value of t_sjpinglun.sjlaiyuanName
     *
     * @mbggenerated
     */
    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjlaiyuanName
     *
     * @param sjlaiyuanName the value for t_sjpinglun.sjlaiyuanName
     *
     * @mbggenerated
     */
    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunImg
     *
     * @return the value of t_sjpinglun.sjpinglunImg
     *
     * @mbggenerated
     */
    public String getSjpinglunImg() {
        return sjpinglunImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunImg
     *
     * @param sjpinglunImg the value for t_sjpinglun.sjpinglunImg
     *
     * @mbggenerated
     */
    public void setSjpinglunImg(String sjpinglunImg) {
        this.sjpinglunImg = sjpinglunImg == null ? null : sjpinglunImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjpinglunImgName
     *
     * @return the value of t_sjpinglun.sjpinglunImgName
     *
     * @mbggenerated
     */
    public String getSjpinglunImgName() {
        return sjpinglunImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjpinglunImgName
     *
     * @param sjpinglunImgName the value for t_sjpinglun.sjpinglunImgName
     *
     * @mbggenerated
     */
    public void setSjpinglunImgName(String sjpinglunImgName) {
        this.sjpinglunImgName = sjpinglunImgName == null ? null : sjpinglunImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.shujuId
     *
     * @return the value of t_sjpinglun.shujuId
     *
     * @mbggenerated
     */
    public Integer getShujuId() {
        return shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.shujuId
     *
     * @param shujuId the value for t_sjpinglun.shujuId
     *
     * @mbggenerated
     */
    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.shujuName
     *
     * @return the value of t_sjpinglun.shujuName
     *
     * @mbggenerated
     */
    public String getShujuName() {
        return shujuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.shujuName
     *
     * @param shujuName the value for t_sjpinglun.shujuName
     *
     * @mbggenerated
     */
    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjleixingId
     *
     * @return the value of t_sjpinglun.sjleixingId
     *
     * @mbggenerated
     */
    public Integer getSjleixingId() {
        return sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjleixingId
     *
     * @param sjleixingId the value for t_sjpinglun.sjleixingId
     *
     * @mbggenerated
     */
    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjleixingName
     *
     * @return the value of t_sjpinglun.sjleixingName
     *
     * @mbggenerated
     */
    public String getSjleixingName() {
        return sjleixingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjleixingName
     *
     * @param sjleixingName the value for t_sjpinglun.sjleixingName
     *
     * @mbggenerated
     */
    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjxingtaiId
     *
     * @return the value of t_sjpinglun.sjxingtaiId
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjxingtaiId
     *
     * @param sjxingtaiId the value for t_sjpinglun.sjxingtaiId
     *
     * @mbggenerated
     */
    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.sjxingtaiName
     *
     * @return the value of t_sjpinglun.sjxingtaiName
     *
     * @mbggenerated
     */
    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.sjxingtaiName
     *
     * @param sjxingtaiName the value for t_sjpinglun.sjxingtaiName
     *
     * @mbggenerated
     */
    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.userId
     *
     * @return the value of t_sjpinglun.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.userId
     *
     * @param userId the value for t_sjpinglun.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.userName
     *
     * @return the value of t_sjpinglun.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.userName
     *
     * @param userName the value for t_sjpinglun.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.bumenId
     *
     * @return the value of t_sjpinglun.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.bumenId
     *
     * @param bumenId the value for t_sjpinglun.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.bumenName
     *
     * @return the value of t_sjpinglun.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.bumenName
     *
     * @param bumenName the value for t_sjpinglun.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.buyuanId
     *
     * @return the value of t_sjpinglun.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.buyuanId
     *
     * @param buyuanId the value for t_sjpinglun.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.buyuanName
     *
     * @return the value of t_sjpinglun.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.buyuanName
     *
     * @param buyuanName the value for t_sjpinglun.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.yonghuId
     *
     * @return the value of t_sjpinglun.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.yonghuId
     *
     * @param yonghuId the value for t_sjpinglun.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.yonghuName
     *
     * @return the value of t_sjpinglun.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.yonghuName
     *
     * @param yonghuName the value for t_sjpinglun.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.buzhiId
     *
     * @return the value of t_sjpinglun.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.buzhiId
     *
     * @param buzhiId the value for t_sjpinglun.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.buzhiName
     *
     * @return the value of t_sjpinglun.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.buzhiName
     *
     * @param buzhiName the value for t_sjpinglun.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.roleId
     *
     * @return the value of t_sjpinglun.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.roleId
     *
     * @param roleId the value for t_sjpinglun.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjpinglun.roleName
     *
     * @return the value of t_sjpinglun.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjpinglun.roleName
     *
     * @param roleName the value for t_sjpinglun.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}